class_weights: !!python/object/apply:torch._utils._rebuild_tensor_v2
- !!python/object/apply:torch.storage._load_from_bytes
  - !!binary |
    gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
    AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
    aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
    Z2UKcQFYDwAAADExMTE0ODIzNjc2NjI0MHECWAMAAABjcHVxA0sETnRxBFEugAJdcQBYDwAAADEx
    MTE0ODIzNjc2NjI0MHEBYS4EAAAAAAAAAM5tQD/gMxZAcahFQKxZBT8=
- 0
- !!python/tuple
  - 4
- !!python/tuple
  - 1
- false
- !!python/object/apply:collections.OrderedDict
  - []
lr: 5.0e-05
max_epochs: 35
num_classes: 4
weight_decay: 1.0e-05
